import './globals.css'
import type { Metadata } from 'next'
import { Red_Hat_Display } from 'next/font/google'
import { useState, useEffect } from 'react'

const red_hat = Red_Hat_Display({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Joel's website",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`debug-screens ${red_hat.className}`}>
        {children}
        </body>
    </html>
  )
}
